name: "build and deploy"
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm install -g pnpm
      - run: pnpm config set registry https://registry.npmmirror.com/
      - run: pnpm install
      - run: pnpm run build

      - run: tar -zcvf release.tgr.gz ./dist/

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "release.tgr.gz"
          target: "/tmp"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd redlnn.top
            tar -xzvf /tmp/release.tgr.gz
            rm -f /tmp/release.tgr.gz
            ./backup.sh html
            mv dist html
