name: 'build and deploy'
on:
  push:
    branches: [vite]
jobs:
  build-and-deploy:
    if: github.actor != 'depbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm config set registry https://registry.npmmirror.com/
          pnpm install
          pnpm minfont
          pnpm build
          tar -zcvf release.tgr.gz ./dist/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'release.tgr.gz'
          target: '/tmp'

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd redlnn.top
            tar -xzvf /tmp/release.tgr.gz
            rm -f /tmp/release.tgr.gz
            ./backup.sh html
            mv dist html
