name: "build and deploy"
on:
  push:
    branches: [ vite ]
jobs:
  build-and-deploy:
    if: github.actor != 'depbot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm config set registry https://registry.npmmirror.com/
      - run: pnpm install
      - run: pnpm run build
      - run: tar -zcvf release.tgr.gz ./dist/
      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "release.tgr.gz"
          target: "/tmp"
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd redlnn.top
            tar -xzvf /tmp/release.tgr.gz
            rm -f /tmp/release.tgr.gz
            ./backup.sh html
            mv dist html
